package handling

//    Copyright 2020 ShiftLeft Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// AtlassianConnect is auto generated by github.com/perrito666/LAC from a json file
type AtlassianConnect struct {
	Authentication Authentication         `json:"authentication,omitempty"`
	BaseURL        string                 `json:"baseUrl,omitempty"`
	Description    string                 `json:"description,omitempty"`
	Key            string                 `json:"key,omitempty"`
	Lifecycle      Lifecycle              `json:"lifecycle,omitempty"`
	Modules        map[string]interface{} `json:"modules,omitempty"`
	Name           string                 `json:"name,omitempty"`
	Scopes         []string               `json:"scopes,omitempty"`
	Vendor         Vendor                 `json:"vendor,omitempty"`
}

// Authentication is auto generated by github.com/perrito666/LAC from a json file
type Authentication struct {
	Type string `json:"type"`
}

// ConditionParams is auto generated by github.com/perrito666/LAC from a json file
type ConditionParams struct {
	Expression string `json:"expression,omitempty"`
}

// Conditions is auto generated by github.com/perrito666/LAC from a json file
type Conditions struct {
	Condition string          `json:"condition,omitempty"`
	Invert    bool            `json:"invert,omitempty"`
	Params    ConditionParams `json:"params,omitempty"`
	Or        []Conditions    `json:"or,omitempty"`
	And       []Conditions    `json:"and,omitempty"`
}

// Description is auto generated by github.com/perrito666/LAC from a json file
type Description struct {
	Value string `json:"value"`
}

// JiraIssueFields is auto generated by github.com/perrito666/LAC from a json file
type JiraIssueFields struct {
	Description Description `json:"description,omitempty"`
	Key         string      `json:"key,omitempty"`
	Name        Name        `json:"name,omitempty"`
	Type        string      `json:"type,omitempty"`
}

// WebPanel is auto generated by github.com/perrito666/LAC from a json file
type WebPanel struct {
	Conditions []Conditions `json:"conditions,omitempty"`
	Context    string       `json:"context,omitempty"`
	Key        string       `json:"key,omitempty"`
	Location   string       `json:"location,omitempty"`
	Name       Name         `json:"name,omitempty"`
	URL        string       `json:"url,omitempty"`
	Weight     float64      `json:"weight,omitempty"`
}

// Lifecycle is auto generated by github.com/perrito666/LAC from a json file
type Lifecycle struct {
	Installed   string `json:"installed,omitempty"`
	UnInstalled string `json:"uninstalled,omitempty"`
	Enabled     string `json:"enabled,omitempty"`
	Disabled    string `json:"disabled,omitempty"`
}

// Name is auto generated by github.com/perrito666/LAC from a json file
type Name struct {
	Value string `json:"value,omitempty"`
}

// Vendor is auto generated by github.com/perrito666/LAC from a json file
type Vendor struct {
	Name string `json:"name,omitempty"`
	URL  string `json:"url,omitempty"`
}

// Webhooks is auto generated by github.com/perrito666/LAC from a json file
type Webhooks struct {
	Event string `json:"event,omitempty"`
	URL   string `json:"url,omitempty"`
}
