package apicommunication

// AttachmentArchiveMetadataReadableJSONEntries is auto generated by github.com/perrito666/LAC from a json file
type AttachmentArchiveMetadataReadableJSONEntries struct {
	Index     float64 `json:"index"`
	Label     string  `json:"label"`
	MediaType string  `json:"mediaType"`
	Path      string  `json:"path"`
	Size      string  `json:"size"`
}

// FailedWebhooksJSONValues is auto generated by github.com/perrito666/LAC from a json file
type FailedWebhooksJSONValues struct {
	Body        string  `json:"body"`
	FailureTime float64 `json:"failureTime"`
	ID          string  `json:"id"`
	URL         string  `json:"url"`
}

// PageBeanContextJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanContextJSONValues struct {
	ID   float64 `json:"id"`
	Name string  `json:"name"`
}

// PageBeanCustomFieldOptionDetailsJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanCustomFieldOptionDetailsJSONValues struct {
	CascadingOptions string  `json:"cascadingOptions"`
	ID               float64 `json:"id"`
	Value            string  `json:"value"`
}

// PageBeanDashboardJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanDashboardJSONValues struct {
	Description      string             `json:"description"`
	ID               string             `json:"id"`
	IsFavourite      bool               `json:"isFavourite"`
	Name             string             `json:"name"`
	Owner            Owner              `json:"owner"`
	Popularity       float64            `json:"popularity"`
	Self             string             `json:"self"`
	SharePermissions []SharePermissions `json:"sharePermissions"`
	View             string             `json:"view"`
}

// PageBeanFieldConfigurationJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfigurationJSONValues struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	IsDefault   bool    `json:"isDefault"`
	Name        string  `json:"name"`
}

// PageBeanIssueFieldOptionJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueFieldOptionJSONValues struct {
	ID         float64    `json:"id"`
	Properties Properties `json:"properties"`
	Value      string     `json:"value"`
}

// PageBeanIssueSecurityLevelMemberJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueSecurityLevelMemberJSONValues struct {
	Holder               Holder  `json:"holder"`
	ID                   float64 `json:"id"`
	IssueSecurityLevelID float64 `json:"issueSecurityLevelId"`
}

// PageBeanNotificationSchemeJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanNotificationSchemeJSONValues struct {
	Description              string                     `json:"description"`
	Expand                   string                     `json:"expand"`
	ID                       float64                    `json:"id"`
	Name                     string                     `json:"name"`
	NotificationSchemeEvents []NotificationSchemeEvents `json:"notificationSchemeEvents"`
	Self                     string                     `json:"self"`
}

// PageBeanScreenJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanScreenJSONValues struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
}

// PageBeanScreenSchemeJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanScreenSchemeJSONValues struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
	Screens     Screens `json:"screens"`
}

// PageBeanWebhookJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWebhookJSONValues struct {
	Events         string  `json:"events"`
	ExpirationDate string  `json:"expirationDate"`
	ID             float64 `json:"id"`
	JqlFilter      string  `json:"jqlFilter"`
}

// PageBeanWorkflowJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWorkflowJSONValues struct {
	Description string              `json:"description"`
	ID          ID                  `json:"id"`
	Statuses    []Statuses          `json:"statuses"`
	Transitions []ValuesTransitions `json:"transitions"`
}

// PageBeanWorkflowSchemeJSONValues is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWorkflowSchemeJSONValues struct {
	DefaultWorkflow   string            `json:"defaultWorkflow"`
	Description       string            `json:"description"`
	Draft             bool              `json:"draft"`
	ID                float64           `json:"id"`
	IssueTypeMappings IssueTypeMappings `json:"issueTypeMappings"`
	Name              string            `json:"name"`
	Self              string            `json:"self"`
}

// PermittedProjectsJSONProjects is auto generated by github.com/perrito666/LAC from a json file
type PermittedProjectsJSONProjects struct {
	ID  float64 `json:"id"`
	Key string  `json:"key"`
}

// ProjectJSONIssueTypes is auto generated by github.com/perrito666/LAC from a json file
type ProjectJSONIssueTypes struct {
	AvatarID    float64 `json:"avatarId"`
	Description string  `json:"description"`
	IconURL     string  `json:"iconUrl"`
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Self        string  `json:"self"`
	Subtask     bool    `json:"subtask"`
}

// ActorGroup is auto generated by github.com/perrito666/LAC from a json file
type ActorGroup struct {
	DisplayName string `json:"displayName"`
	Name        string `json:"name"`
}

// Actors is auto generated by github.com/perrito666/LAC from a json file
type Actors struct {
	ActorGroup  ActorGroup `json:"actorGroup"`
	DisplayName string     `json:"displayName"`
	ID          float64    `json:"id"`
	Name        string     `json:"name"`
	Type        string     `json:"type"`
}

// Application is auto generated by github.com/perrito666/LAC from a json file
type Application struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// ApplicationRole is auto generated by github.com/perrito666/LAC from a json file
type ApplicationRole struct {
	DefaultGroups        string  `json:"defaultGroups"`
	Defined              bool    `json:"defined"`
	Groups               string  `json:"groups"`
	HasUnlimitedSeats    bool    `json:"hasUnlimitedSeats"`
	Key                  string  `json:"key"`
	Name                 string  `json:"name"`
	NumberOfSeats        float64 `json:"numberOfSeats"`
	Platform             bool    `json:"platform"`
	RemainingSeats       float64 `json:"remainingSeats"`
	SelectedByDefault    bool    `json:"selectedByDefault"`
	UserCount            float64 `json:"userCount"`
	UserCountDescription string  `json:"userCountDescription"`
}

// ApplicationRoles is auto generated by github.com/perrito666/LAC from a json file
type ApplicationRoles struct {
	Items []interface{} `json:"items"`
	Size  float64       `json:"size"`
}

// Assignee is auto generated by github.com/perrito666/LAC from a json file
type Assignee struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	AvatarUrls  AvatarURLs `json:"avatarUrls"`
	DisplayName string     `json:"displayName"`
	Key         string     `json:"key"`
	Name        string     `json:"name"`
	Self        string     `json:"self"`
}

// AssociatedItems is auto generated by github.com/perrito666/LAC from a json file
type AssociatedItems struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	ParentID   string `json:"parentId"`
	ParentName string `json:"parentName"`
	TypeName   string `json:"typeName"`
}

// Attachment is auto generated by github.com/perrito666/LAC from a json file
type Attachment struct {
	Author    Author  `json:"author"`
	Content   string  `json:"content"`
	Created   string  `json:"created"`
	Filename  string  `json:"filename"`
	ID        float64 `json:"id"`
	MimeType  string  `json:"mimeType"`
	Self      string  `json:"self"`
	Size      float64 `json:"size"`
	Thumbnail string  `json:"thumbnail"`
}

// AttachmentArchiveImpl is auto generated by github.com/perrito666/LAC from a json file
type AttachmentArchiveImpl struct {
	Entries         []Entries `json:"entries"`
	TotalEntryCount float64   `json:"totalEntryCount"`
}

// AttachmentArchiveMetadataReadable is auto generated by github.com/perrito666/LAC from a json file
type AttachmentArchiveMetadataReadable struct {
	Entries         []AttachmentArchiveMetadataReadableJSONEntries `json:"entries"`
	ID              float64                                        `json:"id"`
	MediaType       string                                         `json:"mediaType"`
	Name            string                                         `json:"name"`
	TotalEntryCount float64                                        `json:"totalEntryCount"`
}

// AttachmentMetadata is auto generated by github.com/perrito666/LAC from a json file
type AttachmentMetadata struct {
	Author    Author  `json:"author"`
	Content   string  `json:"content"`
	Created   string  `json:"created"`
	Filename  string  `json:"filename"`
	ID        float64 `json:"id"`
	MimeType  string  `json:"mimeType"`
	Self      string  `json:"self"`
	Size      float64 `json:"size"`
	Thumbnail string  `json:"thumbnail"`
}

// AttachmentSettings is auto generated by github.com/perrito666/LAC from a json file
type AttachmentSettings struct {
	Enabled     bool    `json:"enabled"`
	UploadLimit float64 `json:"uploadLimit"`
}

// AuditRecords is auto generated by github.com/perrito666/LAC from a json file
type AuditRecords struct {
	Limit   float64   `json:"limit"`
	Offset  float64   `json:"offset"`
	Records []Records `json:"records"`
	Total   float64   `json:"total"`
}

// Author is auto generated by github.com/perrito666/LAC from a json file
type Author struct {
	AccountID    string     `json:"accountId"`
	Active       bool       `json:"active"`
	AvatarUrls   AvatarURLs `json:"avatarUrls"`
	DisplayName  string     `json:"displayName"`
	EmailAddress string     `json:"emailAddress"`
	Key          string     `json:"key"`
	Name         string     `json:"name"`
	Self         string     `json:"self"`
	TimeZone     string     `json:"timeZone"`
}

// AutoCompleteSuggestions is auto generated by github.com/perrito666/LAC from a json file
type AutoCompleteSuggestions struct {
	Results []Results `json:"results"`
}

// Avatar is auto generated by github.com/perrito666/LAC from a json file
type Avatar struct {
	ID             string `json:"id"`
	IsDeletable    bool   `json:"isDeletable"`
	IsSelected     bool   `json:"isSelected"`
	IsSystemAvatar bool   `json:"isSystemAvatar"`
	URLs           URLs   `json:"urls"`
}

// AvatarURLs is auto generated by github.com/perrito666/LAC from a json file
type AvatarURLs struct {
	N16x16 string `json:"16x16"`
	N24x24 string `json:"24x24"`
	N32x32 string `json:"32x32"`
	N48x48 string `json:"48x48"`
}

// Avatars is auto generated by github.com/perrito666/LAC from a json file
type Avatars struct {
	Custom []Custom `json:"custom"`
	System []System `json:"system"`
}

// BULKCHANGE is auto generated by github.com/perrito666/LAC from a json file
type BULKCHANGE struct {
	Description string `json:"description"`
	Key         string `json:"key"`
	Name        string `json:"name"`
	Type        string `json:"type"`
}

// Beans is auto generated by github.com/perrito666/LAC from a json file
type Beans struct {
	Limit float64 `json:"limit"`
	Value float64 `json:"value"`
}

// Body is auto generated by github.com/perrito666/LAC from a json file
type Body struct {
	Content []Content `json:"content"`
	Type    string    `json:"type"`
	Version float64   `json:"version"`
}

// BulkPermissionGrants is auto generated by github.com/perrito666/LAC from a json file
type BulkPermissionGrants struct {
	GlobalPermissions  string               `json:"globalPermissions"`
	ProjectPermissions []ProjectPermissions `json:"projectPermissions"`
}

// ChangedValues is auto generated by github.com/perrito666/LAC from a json file
type ChangedValues struct {
	ChangedFrom string `json:"changedFrom"`
	ChangedTo   string `json:"changedTo"`
	FieldName   string `json:"fieldName"`
}

// ChangedWorklogs is auto generated by github.com/perrito666/LAC from a json file
type ChangedWorklogs struct {
	LastPage bool     `json:"lastPage"`
	NextPage string   `json:"nextPage"`
	Self     string   `json:"self"`
	Since    float64  `json:"since"`
	Until    float64  `json:"until"`
	Values   []Values `json:"values"`
}

// Clauses is auto generated by github.com/perrito666/LAC from a json file
type Clauses struct {
	Field    Field   `json:"field"`
	Operand  Operand `json:"operand"`
	Operator string  `json:"operator"`
}

// Comment is auto generated by github.com/perrito666/LAC from a json file
type Comment struct {
	Author       Author       `json:"author"`
	Body         Body         `json:"body"`
	Content      []Content    `json:"content"`
	Created      string       `json:"created"`
	ID           string       `json:"id"`
	Self         string       `json:"self"`
	Type         string       `json:"type"`
	UpdateAuthor UpdateAuthor `json:"updateAuthor"`
	Updated      string       `json:"updated"`
	Version      float64      `json:"version"`
	Visibility   Visibility   `json:"visibility"`
}

// Comments is auto generated by github.com/perrito666/LAC from a json file
type Comments struct {
	Author       Author       `json:"author"`
	Body         Body         `json:"body"`
	Created      string       `json:"created"`
	ID           string       `json:"id"`
	Self         string       `json:"self"`
	UpdateAuthor UpdateAuthor `json:"updateAuthor"`
	Updated      string       `json:"updated"`
	Visibility   Visibility   `json:"visibility"`
}

// Complexity is auto generated by github.com/perrito666/LAC from a json file
type Complexity struct {
	Beans               Beans               `json:"beans"`
	ExpensiveOperations ExpensiveOperations `json:"expensiveOperations"`
	PrimitiveValues     PrimitiveValues     `json:"primitiveValues"`
	Steps               Steps               `json:"steps"`
}

// Component is auto generated by github.com/perrito666/LAC from a json file
type Component struct {
	Assignee            Assignee     `json:"assignee"`
	AssigneeType        string       `json:"assigneeType"`
	Description         string       `json:"description"`
	ID                  string       `json:"id"`
	IsAssigneeTypeValID bool         `json:"isAssigneeTypeValid"`
	Lead                Lead         `json:"lead"`
	Name                string       `json:"name"`
	Project             string       `json:"project"`
	ProjectID           float64      `json:"projectId"`
	RealAssignee        RealAssignee `json:"realAssignee"`
	RealAssigneeType    string       `json:"realAssigneeType"`
	Self                string       `json:"self"`
}

// ComponentBean is auto generated by github.com/perrito666/LAC from a json file
type ComponentBean struct {
	Assignee            Assignee     `json:"assignee"`
	AssigneeType        string       `json:"assigneeType"`
	Description         string       `json:"description"`
	ID                  string       `json:"id"`
	IsAssigneeTypeValID bool         `json:"isAssigneeTypeValid"`
	Lead                Lead         `json:"lead"`
	Name                string       `json:"name"`
	Project             string       `json:"project"`
	ProjectID           float64      `json:"projectId"`
	RealAssignee        RealAssignee `json:"realAssignee"`
	RealAssigneeType    string       `json:"realAssigneeType"`
	Self                string       `json:"self"`
}

// ComponentIssuesCount is auto generated by github.com/perrito666/LAC from a json file
type ComponentIssuesCount struct {
	IssueCount float64 `json:"issueCount"`
	Self       string  `json:"self"`
}

// Components is auto generated by github.com/perrito666/LAC from a json file
type Components struct {
	Assignee            Assignee     `json:"assignee"`
	AssigneeType        string       `json:"assigneeType"`
	Description         string       `json:"description"`
	ID                  string       `json:"id"`
	IsAssigneeTypeValID bool         `json:"isAssigneeTypeValid"`
	Lead                Lead         `json:"lead"`
	Name                string       `json:"name"`
	Project             string       `json:"project"`
	ProjectID           float64      `json:"projectId"`
	RealAssignee        RealAssignee `json:"realAssignee"`
	RealAssigneeType    string       `json:"realAssigneeType"`
	Self                string       `json:"self"`
}

// Conditions is auto generated by github.com/perrito666/LAC from a json file
type Conditions struct {
	Configuration Configuration `json:"configuration"`
	ID            string        `json:"id"`
	Key           string        `json:"key"`
	Transition    Transition    `json:"transition"`
	Type          string        `json:"type"`
}

// Config is auto generated by github.com/perrito666/LAC from a json file
type Config struct {
	Attributes []interface{} `json:"attributes"`
	Scope      Scope         `json:"scope"`
}

// Configuration is auto generated by github.com/perrito666/LAC from a json file
type Configuration struct {
	AttachmentsEnabled        bool                      `json:"attachmentsEnabled"`
	ErrorMessage              string                    `json:"errorMessage"`
	Fields                    string                    `json:"fields"`
	IgnoreContext             bool                      `json:"ignoreContext"`
	IssueLinkingEnabled       bool                      `json:"issueLinkingEnabled"`
	PermissionKey             string                    `json:"permissionKey"`
	SubTasksEnabled           bool                      `json:"subTasksEnabled"`
	TimeTrackingConfiguration TimeTrackingConfiguration `json:"timeTrackingConfiguration"`
	TimeTrackingEnabled       bool                      `json:"timeTrackingEnabled"`
	UnassignedIssuesAllowed   bool                      `json:"unassignedIssuesAllowed"`
	Value                     string                    `json:"value"`
	VotingEnabled             bool                      `json:"votingEnabled"`
	WatchingEnabled           bool                      `json:"watchingEnabled"`
}

// ContainerForRegisteredWebhooks is auto generated by github.com/perrito666/LAC from a json file
type ContainerForRegisteredWebhooks struct {
	WebhookRegistrationResult []WebhookRegistrationResult `json:"webhookRegistrationResult"`
}

// ContainerOfWorkflowSchemeAssociations is auto generated by github.com/perrito666/LAC from a json file
type ContainerOfWorkflowSchemeAssociations struct {
	Values []Values `json:"values"`
}

// Content is auto generated by github.com/perrito666/LAC from a json file
type Content struct {
	Content []Content `json:"content"`
	Text    string    `json:"text"`
	Type    string    `json:"type"`
}

// ConvertedJQLQueries is auto generated by github.com/perrito666/LAC from a json file
type ConvertedJQLQueries struct {
	QueriesWithUnknownUsers []QueriesWithUnknownUsers `json:"queriesWithUnknownUsers"`
	QueryStrings            string                    `json:"queryStrings"`
}

// CreatedIssue is auto generated by github.com/perrito666/LAC from a json file
type CreatedIssue struct {
	ID         string     `json:"id"`
	Key        string     `json:"key"`
	Self       string     `json:"self"`
	Transition Transition `json:"transition"`
}

// CreatedIssues is auto generated by github.com/perrito666/LAC from a json file
type CreatedIssues struct {
	Errors []interface{} `json:"errors"`
	Issues []Issues      `json:"issues"`
}

// Custom is auto generated by github.com/perrito666/LAC from a json file
type Custom struct {
	ID             string `json:"id"`
	IsDeletable    bool   `json:"isDeletable"`
	IsSelected     bool   `json:"isSelected"`
	IsSystemAvatar bool   `json:"isSystemAvatar"`
	URLs           URLs   `json:"urls"`
}

// CustomFieldContextOptionsList is auto generated by github.com/perrito666/LAC from a json file
type CustomFieldContextOptionsList struct {
	Options []Options `json:"options"`
}

// CustomFieldOption is auto generated by github.com/perrito666/LAC from a json file
type CustomFieldOption struct {
	Self  string `json:"self"`
	Value string `json:"value"`
}

// CustomFieldUsage is auto generated by github.com/perrito666/LAC from a json file
type CustomFieldUsage struct {
	CustomFieldID                      float64 `json:"customFieldId"`
	FieldName                          string  `json:"fieldName"`
	IssueCountWithVersionInCustomField float64 `json:"issueCountWithVersionInCustomField"`
}

// Dashboard is auto generated by github.com/perrito666/LAC from a json file
type Dashboard struct {
	ID               string             `json:"id"`
	IsFavourite      bool               `json:"isFavourite"`
	Name             string             `json:"name"`
	Popularity       float64            `json:"popularity"`
	Self             string             `json:"self"`
	SharePermissions []SharePermissions `json:"sharePermissions"`
	View             string             `json:"view"`
}

// Dashboards is auto generated by github.com/perrito666/LAC from a json file
type Dashboards struct {
	ID               string             `json:"id"`
	IsFavourite      bool               `json:"isFavourite"`
	Name             string             `json:"name"`
	Popularity       float64            `json:"popularity"`
	Self             string             `json:"self"`
	SharePermissions []SharePermissions `json:"sharePermissions"`
	View             string             `json:"view"`
}

// DefaultLocale is auto generated by github.com/perrito666/LAC from a json file
type DefaultLocale struct {
	Locale string `json:"locale"`
}

// DefaultShareScope is auto generated by github.com/perrito666/LAC from a json file
type DefaultShareScope struct {
	Scope string `json:"scope"`
}

// DefaultWorkflow is auto generated by github.com/perrito666/LAC from a json file
type DefaultWorkflow struct {
	Workflow string `json:"workflow"`
}

// Description is auto generated by github.com/perrito666/LAC from a json file
type Description struct {
	Content []Content `json:"content"`
	Type    string    `json:"type"`
	Version float64   `json:"version"`
}

// EntityProperty is auto generated by github.com/perrito666/LAC from a json file
type EntityProperty struct {
	Key   string `json:"key"`
	Self  string `json:"self"`
	Value string `json:"value"`
}

// Entries is auto generated by github.com/perrito666/LAC from a json file
type Entries struct {
	EntryIndex float64 `json:"entryIndex"`
	MediaType  string  `json:"mediaType"`
	Name       string  `json:"name"`
	Size       float64 `json:"size"`
}

// ErrorCollection is auto generated by github.com/perrito666/LAC from a json file
type ErrorCollection struct {
	ErrorMessages []interface{} `json:"errorMessages"`
	Errors        Errors        `json:"errors"`
}

// Errors is auto generated by github.com/perrito666/LAC from a json file
type Errors struct {
	Column     float64 `json:"column"`
	Line       float64 `json:"line"`
	Message    string  `json:"message"`
	ProjectKey string  `json:"projectKey"`
	Type       string  `json:"type"`
}

// Event is auto generated by github.com/perrito666/LAC from a json file
type Event struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
}

// ExpensiveOperations is auto generated by github.com/perrito666/LAC from a json file
type ExpensiveOperations struct {
	Limit float64 `json:"limit"`
	Value float64 `json:"value"`
}

// FailedWebhooks is auto generated by github.com/perrito666/LAC from a json file
type FailedWebhooks struct {
	MaxResults float64                    `json:"maxResults"`
	Next       string                     `json:"next"`
	Values     []FailedWebhooksJSONValues `json:"values"`
}

// Field is auto generated by github.com/perrito666/LAC from a json file
type Field struct {
	Name string `json:"name"`
}

// FieldDetails is auto generated by github.com/perrito666/LAC from a json file
type FieldDetails struct {
	ClauseNames      string `json:"clauseNames"`
	Custom           bool   `json:"custom"`
	ID               string `json:"id"`
	Key              string `json:"key"`
	Name             string `json:"name"`
	Navigable        bool   `json:"navigable"`
	Orderable        bool   `json:"orderable"`
	Schema           Schema `json:"schema"`
	Searchable       bool   `json:"searchable"`
	UntranslatedName string `json:"untranslatedName"`
}

// Fields is auto generated by github.com/perrito666/LAC from a json file
type Fields struct {
	Attachment   []Attachment `json:"attachment"`
	Comment      []Comment    `json:"comment"`
	Description  Description  `json:"description"`
	Direction    string       `json:"direction"`
	Field        Field        `json:"field"`
	Issuelinks   []Issuelinks `json:"issuelinks"`
	Issuetype    Issuetype    `json:"issuetype"`
	Priority     Priority     `json:"priority"`
	Project      Project      `json:"project"`
	Status       Status       `json:"status"`
	SubTasks     []SubTasks   `json:"sub-tasks"`
	Summary      Summary      `json:"summary"`
	Timetracking Timetracking `json:"timetracking"`
	Updated      float64      `json:"updated"`
	Watcher      Watcher      `json:"watcher"`
	Worklog      []Worklog    `json:"worklog"`
}

// Filter is auto generated by github.com/perrito666/LAC from a json file
type Filter struct {
	Description      string        `json:"description"`
	Favourite        bool          `json:"favourite"`
	FavouritedCount  float64       `json:"favouritedCount"`
	ID               string        `json:"id"`
	Jql              string        `json:"jql"`
	Name             string        `json:"name"`
	Owner            Owner         `json:"owner"`
	SearchURL        string        `json:"searchUrl"`
	Self             string        `json:"self"`
	SharePermissions []interface{} `json:"sharePermissions"`
	Subscriptions    Subscriptions `json:"subscriptions"`
	ViewURL          string        `json:"viewUrl"`
}

// FoundGroups is auto generated by github.com/perrito666/LAC from a json file
type FoundGroups struct {
	Groups []Groups `json:"groups"`
	Header string   `json:"header"`
	Total  float64  `json:"total"`
}

// FoundUsers is auto generated by github.com/perrito666/LAC from a json file
type FoundUsers struct {
	Header string  `json:"header"`
	Total  float64 `json:"total"`
	Users  []Users `json:"users"`
}

// FoundUsersAndGroups is auto generated by github.com/perrito666/LAC from a json file
type FoundUsersAndGroups struct {
	Groups Groups `json:"groups"`
	Users  Users  `json:"users"`
}

// Global is auto generated by github.com/perrito666/LAC from a json file
type Global struct {
}

// Group is auto generated by github.com/perrito666/LAC from a json file
type Group struct {
	Expand string `json:"expand"`
	Name   string `json:"name"`
	Self   string `json:"self"`
	Users  Users  `json:"users"`
}

// Groups is auto generated by github.com/perrito666/LAC from a json file
type Groups struct {
	GroupID string        `json:"groupId"`
	Groups  []Groups      `json:"groups"`
	Header  string        `json:"header"`
	HTML    string        `json:"html"`
	Items   []interface{} `json:"items"`
	Name    string        `json:"name"`
	Size    float64       `json:"size"`
	Total   float64       `json:"total"`
}

// Hierarchy is auto generated by github.com/perrito666/LAC from a json file
type Hierarchy struct {
	EntityID   string       `json:"entityId"`
	IssueTypes []IssueTypes `json:"issueTypes"`
	Level      float64      `json:"level"`
	Name       string       `json:"name"`
}

// Holder is auto generated by github.com/perrito666/LAC from a json file
type Holder struct {
	Expand    string `json:"expand"`
	Parameter string `json:"parameter"`
	Type      string `json:"type"`
	User      User   `json:"user"`
}

// Icon is auto generated by github.com/perrito666/LAC from a json file
type Icon struct {
	Link     string `json:"link"`
	Title    string `json:"title"`
	URL16x16 string `json:"url16x16"`
}

// ID is auto generated by github.com/perrito666/LAC from a json file
type ID struct {
	Name string `json:"name"`
}

// Insight is auto generated by github.com/perrito666/LAC from a json file
type Insight struct {
	LastIssueUpdateTime string  `json:"lastIssueUpdateTime"`
	TotalIssueCount     float64 `json:"totalIssueCount"`
}

// InwardIssue is auto generated by github.com/perrito666/LAC from a json file
type InwardIssue struct {
	Fields Fields `json:"fields"`
	ID     string `json:"id"`
	Key    string `json:"key"`
	Self   string `json:"self"`
}

// IssueBean is auto generated by github.com/perrito666/LAC from a json file
type IssueBean struct {
	Expand string `json:"expand"`
	Fields Fields `json:"fields"`
	ID     string `json:"id"`
	Key    string `json:"key"`
	Self   string `json:"self"`
}

// IssueCreateMetadata is auto generated by github.com/perrito666/LAC from a json file
type IssueCreateMetadata struct {
	Projects []Projects `json:"projects"`
}

// IssueFieldOption is auto generated by github.com/perrito666/LAC from a json file
type IssueFieldOption struct {
	Config     Config     `json:"config"`
	ID         float64    `json:"id"`
	Properties Properties `json:"properties"`
	Value      string     `json:"value"`
}

// IssueLink is auto generated by github.com/perrito666/LAC from a json file
type IssueLink struct {
	ID           string       `json:"id"`
	InwardIssue  InwardIssue  `json:"inwardIssue"`
	OutwardIssue OutwardIssue `json:"outwardIssue"`
	Type         Type         `json:"type"`
}

// IssueLinkType is auto generated by github.com/perrito666/LAC from a json file
type IssueLinkType struct {
	ID      string `json:"id"`
	Inward  string `json:"inward"`
	Name    string `json:"name"`
	Outward string `json:"outward"`
	Self    string `json:"self"`
}

// IssueLinkTypes is auto generated by github.com/perrito666/LAC from a json file
type IssueLinkTypes struct {
	ID             string           `json:"id"`
	Inward         string           `json:"inward"`
	IssueLinkTypes []IssueLinkTypes `json:"issueLinkTypes"`
	Name           string           `json:"name"`
	Outward        string           `json:"outward"`
	Self           string           `json:"self"`
}

// IssueMatches is auto generated by github.com/perrito666/LAC from a json file
type IssueMatches struct {
	Matches []Matches `json:"matches"`
}

// IssueSecuritySchemes is auto generated by github.com/perrito666/LAC from a json file
type IssueSecuritySchemes struct {
	DefaultSecurityLevelID float64 `json:"defaultSecurityLevelId"`
	Description            string  `json:"description"`
	ID                     float64 `json:"id"`
	Name                   string  `json:"name"`
	Self                   string  `json:"self"`
}

// IssueTypeDetails is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeDetails struct {
	AvatarID    float64 `json:"avatarId"`
	Description string  `json:"description"`
	IconURL     string  `json:"iconUrl"`
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Self        string  `json:"self"`
	Subtask     bool    `json:"subtask"`
}

// IssueTypeMappings is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeMappings struct {
	N10000 string `json:"10000"`
	N10001 string `json:"10001"`
}

// IssueTypeScheme is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeScheme struct {
	DefaultIssueTypeID string `json:"defaultIssueTypeId"`
	Description        string `json:"description"`
	ID                 string `json:"id"`
	IsDefault          bool   `json:"isDefault"`
	Name               string `json:"name"`
}

// IssueTypeSchemeID is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeSchemeID struct {
	IssueTypeSchemeID string `json:"issueTypeSchemeId"`
}

// IssueTypeScreenScheme is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeScreenScheme struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}

// IssueTypeScreenSchemeID is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeScreenSchemeID struct {
	ID string `json:"id"`
}

// IssueTypeWorkflowMapping is auto generated by github.com/perrito666/LAC from a json file
type IssueTypeWorkflowMapping struct {
	IssueType string `json:"issueType"`
	Workflow  string `json:"workflow"`
}

// IssueTypes is auto generated by github.com/perrito666/LAC from a json file
type IssueTypes struct {
	AvatarID float64 `json:"avatarId"`
	EntityID string  `json:"entityId"`
	ID       float64 `json:"id"`
	Name     string  `json:"name"`
}

// IssueTypesWorkflowMapping is auto generated by github.com/perrito666/LAC from a json file
type IssueTypesWorkflowMapping struct {
	DefaultMapping bool   `json:"defaultMapping"`
	IssueTypes     string `json:"issueTypes"`
	Workflow       string `json:"workflow"`
}

// IssueUpdateMetadata is auto generated by github.com/perrito666/LAC from a json file
type IssueUpdateMetadata struct {
	Fields Fields `json:"fields"`
}

// Issuelinks is auto generated by github.com/perrito666/LAC from a json file
type Issuelinks struct {
	ID           string       `json:"id"`
	OutwardIssue OutwardIssue `json:"outwardIssue"`
	Type         Type         `json:"type"`
}

// Issues is auto generated by github.com/perrito666/LAC from a json file
type Issues struct {
	Expand     string     `json:"expand"`
	Fields     Fields     `json:"fields"`
	ID         string     `json:"id"`
	Jql        Jql        `json:"jql"`
	Key        string     `json:"key"`
	Self       string     `json:"self"`
	Transition Transition `json:"transition"`
}

// Issuetype is auto generated by github.com/perrito666/LAC from a json file
type Issuetype struct {
	AvatarID        float64 `json:"avatarId"`
	Description     string  `json:"description"`
	EntityID        string  `json:"entityId"`
	HasDefaultValue bool    `json:"hasDefaultValue"`
	IconURL         string  `json:"iconUrl"`
	ID              string  `json:"id"`
	Key             string  `json:"key"`
	Name            string  `json:"name"`
	Operations      string  `json:"operations"`
	Required        bool    `json:"required"`
	Scope           Scope   `json:"scope"`
	Self            string  `json:"self"`
	Subtask         bool    `json:"subtask"`
}

// Issuetypes is auto generated by github.com/perrito666/LAC from a json file
type Issuetypes struct {
	Description string `json:"description"`
	Fields      Fields `json:"fields"`
	IconURL     string `json:"iconUrl"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
	Subtask     bool   `json:"subtask"`
}

// Items is auto generated by github.com/perrito666/LAC from a json file
type Items struct {
	AccountID   string      `json:"accountId"`
	Active      bool        `json:"active"`
	DisplayName string      `json:"displayName"`
	Field       string      `json:"field"`
	FieldID     string      `json:"fieldId"`
	Fieldtype   string      `json:"fieldtype"`
	From        interface{} `json:"from"`
	FromString  string      `json:"fromString"`
	Self        string      `json:"self"`
	To          interface{} `json:"to"`
	ToString    string      `json:"toString"`
}

// JQLReferenceData is auto generated by github.com/perrito666/LAC from a json file
type JQLReferenceData struct {
	JqlReservedWords     string                 `json:"jqlReservedWords"`
	VisibleFieldNames    []VisibleFieldNames    `json:"visibleFieldNames"`
	VisibleFunctionNames []VisibleFunctionNames `json:"visibleFunctionNames"`
}

// JiraExpressionResult is auto generated by github.com/perrito666/LAC from a json file
type JiraExpressionResult struct {
	Meta  Meta   `json:"meta"`
	Value string `json:"value"`
}

// JiraExpressionsAnalysis is auto generated by github.com/perrito666/LAC from a json file
type JiraExpressionsAnalysis struct {
	Results []Results `json:"results"`
}

// Jql is auto generated by github.com/perrito666/LAC from a json file
type Jql struct {
	Count              float64 `json:"count"`
	MaxResults         float64 `json:"maxResults"`
	StartAt            float64 `json:"startAt"`
	TotalCount         float64 `json:"totalCount"`
	ValidationWarnings string  `json:"validationWarnings"`
}

// Keys is auto generated by github.com/perrito666/LAC from a json file
type Keys struct {
	Key  string `json:"key"`
	Self string `json:"self"`
}

// LastUsed is auto generated by github.com/perrito666/LAC from a json file
type LastUsed struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

// Lead is auto generated by github.com/perrito666/LAC from a json file
type Lead struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	AvatarUrls  AvatarURLs `json:"avatarUrls"`
	DisplayName string     `json:"displayName"`
	Key         string     `json:"key"`
	Name        string     `json:"name"`
	Self        string     `json:"self"`
}

// Leader is auto generated by github.com/perrito666/LAC from a json file
type Leader struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// Levels is auto generated by github.com/perrito666/LAC from a json file
type Levels struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
}

// Locale is auto generated by github.com/perrito666/LAC from a json file
type Locale struct {
	Locale string `json:"locale"`
}

// Matches is auto generated by github.com/perrito666/LAC from a json file
type Matches struct {
	Errors        []interface{} `json:"errors"`
	MatchedIssues float64       `json:"matchedIssues"`
}

// Meta is auto generated by github.com/perrito666/LAC from a json file
type Meta struct {
	Complexity Complexity `json:"complexity"`
	Issues     Issues     `json:"issues"`
}

// NotificationScheme is auto generated by github.com/perrito666/LAC from a json file
type NotificationScheme struct {
	Description              string                     `json:"description"`
	Expand                   string                     `json:"expand"`
	ID                       float64                    `json:"id"`
	Name                     string                     `json:"name"`
	NotificationSchemeEvents []NotificationSchemeEvents `json:"notificationSchemeEvents"`
	Self                     string                     `json:"self"`
}

// NotificationSchemeEvents is auto generated by github.com/perrito666/LAC from a json file
type NotificationSchemeEvents struct {
	Event         Event           `json:"event"`
	Notifications []Notifications `json:"notifications"`
}

// Notifications is auto generated by github.com/perrito666/LAC from a json file
type Notifications struct {
	Expand           string  `json:"expand"`
	Group            Group   `json:"group"`
	ID               float64 `json:"id"`
	NotificationType string  `json:"notificationType"`
	Parameter        string  `json:"parameter"`
}

// Object is auto generated by github.com/perrito666/LAC from a json file
type Object struct {
	Icon    Icon   `json:"icon"`
	Status  Status `json:"status"`
	Summary string `json:"summary"`
	Title   string `json:"title"`
	URL     string `json:"url"`
}

// ObjectItem is auto generated by github.com/perrito666/LAC from a json file
type ObjectItem struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	ParentID   string `json:"parentId"`
	ParentName string `json:"parentName"`
	TypeName   string `json:"typeName"`
}

// Operand is auto generated by github.com/perrito666/LAC from a json file
type Operand struct {
	Value string `json:"value"`
}

// OperationMessage is auto generated by github.com/perrito666/LAC from a json file
type OperationMessage struct {
	Message    string  `json:"message"`
	StatusCode float64 `json:"statusCode"`
}

// Options is auto generated by github.com/perrito666/LAC from a json file
type Options struct {
	Disabled bool   `json:"disabled"`
	ID       string `json:"id"`
	Value    string `json:"value"`
}

// OrderBy is auto generated by github.com/perrito666/LAC from a json file
type OrderBy struct {
	Fields []Fields `json:"fields"`
}

// OutwardIssue is auto generated by github.com/perrito666/LAC from a json file
type OutwardIssue struct {
	Fields Fields `json:"fields"`
	ID     string `json:"id"`
	Key    string `json:"key"`
	Self   string `json:"self"`
}

// Owner is auto generated by github.com/perrito666/LAC from a json file
type Owner struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	AvatarUrls  AvatarURLs `json:"avatarUrls"`
	DisplayName string     `json:"displayName"`
	Key         string     `json:"key"`
	Name        string     `json:"name"`
	Self        string     `json:"self"`
}

// PageBeanChangelog is auto generated by github.com/perrito666/LAC from a json file
type PageBeanChangelog struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	NextPage   string   `json:"nextPage"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanComment is auto generated by github.com/perrito666/LAC from a json file
type PageBeanComment struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanComponentWithIssueCount is auto generated by github.com/perrito666/LAC from a json file
type PageBeanComponentWithIssueCount struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	NextPage   string   `json:"nextPage"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanContext is auto generated by github.com/perrito666/LAC from a json file
type PageBeanContext struct {
	IsLast     bool                        `json:"isLast"`
	MaxResults float64                     `json:"maxResults"`
	StartAt    float64                     `json:"startAt"`
	Total      float64                     `json:"total"`
	Values     []PageBeanContextJSONValues `json:"values"`
}

// PageBeanCustomFieldContextOption is auto generated by github.com/perrito666/LAC from a json file
type PageBeanCustomFieldContextOption struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanCustomFieldOptionDetails is auto generated by github.com/perrito666/LAC from a json file
type PageBeanCustomFieldOptionDetails struct {
	IsLast     bool                                         `json:"isLast"`
	MaxResults float64                                      `json:"maxResults"`
	StartAt    float64                                      `json:"startAt"`
	Total      float64                                      `json:"total"`
	Values     []PageBeanCustomFieldOptionDetailsJSONValues `json:"values"`
}

// PageBeanDashboard is auto generated by github.com/perrito666/LAC from a json file
type PageBeanDashboard struct {
	IsLast     bool                          `json:"isLast"`
	MaxResults float64                       `json:"maxResults"`
	Self       string                        `json:"self"`
	StartAt    float64                       `json:"startAt"`
	Total      float64                       `json:"total"`
	Values     []PageBeanDashboardJSONValues `json:"values"`
}

// PageBeanField is auto generated by github.com/perrito666/LAC from a json file
type PageBeanField struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanFieldConfiguration is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfiguration struct {
	IsLast     bool                                   `json:"isLast"`
	MaxResults float64                                `json:"maxResults"`
	StartAt    float64                                `json:"startAt"`
	Total      float64                                `json:"total"`
	Values     []PageBeanFieldConfigurationJSONValues `json:"values"`
}

// PageBeanFieldConfigurationIssueTypeItem is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfigurationIssueTypeItem struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanFieldConfigurationItem is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfigurationItem struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanFieldConfigurationScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfigurationScheme struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanFieldConfigurationSchemeProjects is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFieldConfigurationSchemeProjects struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanFilterDetails is auto generated by github.com/perrito666/LAC from a json file
type PageBeanFilterDetails struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanGroupDetails is auto generated by github.com/perrito666/LAC from a json file
type PageBeanGroupDetails struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueFieldOption is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueFieldOption struct {
	IsLast     bool                                 `json:"isLast"`
	MaxResults float64                              `json:"maxResults"`
	NextPage   string                               `json:"nextPage"`
	Self       string                               `json:"self"`
	StartAt    float64                              `json:"startAt"`
	Total      float64                              `json:"total"`
	Values     []PageBeanIssueFieldOptionJSONValues `json:"values"`
}

// PageBeanIssueSecurityLevelMember is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueSecurityLevelMember struct {
	IsLast     bool                                         `json:"isLast"`
	MaxResults float64                                      `json:"maxResults"`
	StartAt    float64                                      `json:"startAt"`
	Total      float64                                      `json:"total"`
	Values     []PageBeanIssueSecurityLevelMemberJSONValues `json:"values"`
}

// PageBeanIssueTypeScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeScheme struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueTypeSchemeMapping is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeSchemeMapping struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueTypeSchemeProjects is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeSchemeProjects struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueTypeScreenScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeScreenScheme struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueTypeScreenSchemeItem is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeScreenSchemeItem struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanIssueTypeScreenSchemesProjects is auto generated by github.com/perrito666/LAC from a json file
type PageBeanIssueTypeScreenSchemesProjects struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanNotificationScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanNotificationScheme struct {
	IsLast     bool                                   `json:"isLast"`
	MaxResults float64                                `json:"maxResults"`
	StartAt    float64                                `json:"startAt"`
	Total      float64                                `json:"total"`
	Values     []PageBeanNotificationSchemeJSONValues `json:"values"`
}

// PageBeanProject is auto generated by github.com/perrito666/LAC from a json file
type PageBeanProject struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	NextPage   string   `json:"nextPage"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanScreen is auto generated by github.com/perrito666/LAC from a json file
type PageBeanScreen struct {
	IsLast     bool                       `json:"isLast"`
	MaxResults float64                    `json:"maxResults"`
	Self       string                     `json:"self"`
	StartAt    float64                    `json:"startAt"`
	Total      float64                    `json:"total"`
	Values     []PageBeanScreenJSONValues `json:"values"`
}

// PageBeanScreenScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanScreenScheme struct {
	IsLast     bool                             `json:"isLast"`
	MaxResults float64                          `json:"maxResults"`
	Self       string                           `json:"self"`
	StartAt    float64                          `json:"startAt"`
	Total      float64                          `json:"total"`
	Values     []PageBeanScreenSchemeJSONValues `json:"values"`
}

// PageBeanString is auto generated by github.com/perrito666/LAC from a json file
type PageBeanString struct {
	IsLast     bool    `json:"isLast"`
	MaxResults float64 `json:"maxResults"`
	StartAt    float64 `json:"startAt"`
	Total      float64 `json:"total"`
	Values     string  `json:"values"`
}

// PageBeanUser is auto generated by github.com/perrito666/LAC from a json file
type PageBeanUser struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanUserDetails is auto generated by github.com/perrito666/LAC from a json file
type PageBeanUserDetails struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	NextPage   string   `json:"nextPage"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanVersion is auto generated by github.com/perrito666/LAC from a json file
type PageBeanVersion struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	NextPage   string   `json:"nextPage"`
	Self       string   `json:"self"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageBeanWebhook is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWebhook struct {
	IsLast     bool                        `json:"isLast"`
	MaxResults float64                     `json:"maxResults"`
	StartAt    float64                     `json:"startAt"`
	Total      float64                     `json:"total"`
	Values     []PageBeanWebhookJSONValues `json:"values"`
}

// PageBeanWorkflow is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWorkflow struct {
	IsLast     bool                         `json:"isLast"`
	MaxResults float64                      `json:"maxResults"`
	StartAt    float64                      `json:"startAt"`
	Total      float64                      `json:"total"`
	Values     []PageBeanWorkflowJSONValues `json:"values"`
}

// PageBeanWorkflowScheme is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWorkflowScheme struct {
	IsLast     bool                               `json:"isLast"`
	MaxResults float64                            `json:"maxResults"`
	StartAt    float64                            `json:"startAt"`
	Total      float64                            `json:"total"`
	Values     []PageBeanWorkflowSchemeJSONValues `json:"values"`
}

// PageBeanWorkflowTransitionRules is auto generated by github.com/perrito666/LAC from a json file
type PageBeanWorkflowTransitionRules struct {
	IsLast     bool     `json:"isLast"`
	MaxResults float64  `json:"maxResults"`
	StartAt    float64  `json:"startAt"`
	Total      float64  `json:"total"`
	Values     []Values `json:"values"`
}

// PageOfComments is auto generated by github.com/perrito666/LAC from a json file
type PageOfComments struct {
	Comments   []Comments `json:"comments"`
	MaxResults float64    `json:"maxResults"`
	StartAt    float64    `json:"startAt"`
	Total      float64    `json:"total"`
}

// PageOfDashboards is auto generated by github.com/perrito666/LAC from a json file
type PageOfDashboards struct {
	Dashboards []Dashboards `json:"dashboards"`
	MaxResults float64      `json:"maxResults"`
	Next       string       `json:"next"`
	Prev       string       `json:"prev"`
	StartAt    float64      `json:"startAt"`
	Total      float64      `json:"total"`
}

// PageOfWorklogs is auto generated by github.com/perrito666/LAC from a json file
type PageOfWorklogs struct {
	MaxResults float64    `json:"maxResults"`
	StartAt    float64    `json:"startAt"`
	Total      float64    `json:"total"`
	Worklogs   []Worklogs `json:"worklogs"`
}

// ParsedJqlQueries is auto generated by github.com/perrito666/LAC from a json file
type ParsedJqlQueries struct {
	Queries []Queries `json:"queries"`
}

// PermissionGrant is auto generated by github.com/perrito666/LAC from a json file
type PermissionGrant struct {
	Holder     Holder  `json:"holder"`
	ID         float64 `json:"id"`
	Permission string  `json:"permission"`
	Self       string  `json:"self"`
}

// PermissionGrants is auto generated by github.com/perrito666/LAC from a json file
type PermissionGrants struct {
	Expand      string        `json:"expand"`
	Permissions []Permissions `json:"permissions"`
}

// PermissionScheme is auto generated by github.com/perrito666/LAC from a json file
type PermissionScheme struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
	Self        string  `json:"self"`
}

// PermissionSchemes is auto generated by github.com/perrito666/LAC from a json file
type PermissionSchemes struct {
	Description       string              `json:"description"`
	ID                float64             `json:"id"`
	Name              string              `json:"name"`
	PermissionSchemes []PermissionSchemes `json:"permissionSchemes"`
	Self              string              `json:"self"`
}

// Permissions is auto generated by github.com/perrito666/LAC from a json file
type Permissions struct {
	BULKCHANGE  BULKCHANGE   `json:"BULK_CHANGE"`
	Holder      Holder       `json:"holder"`
	ID          float64      `json:"id"`
	Permission  string       `json:"permission"`
	Permissions *Permissions `json:"permissions"`
	Self        string       `json:"self"`
}

// PermittedProjects is auto generated by github.com/perrito666/LAC from a json file
type PermittedProjects struct {
	Projects []PermittedProjectsJSONProjects `json:"projects"`
}

// PostFunctions is auto generated by github.com/perrito666/LAC from a json file
type PostFunctions struct {
	Configuration Configuration `json:"configuration"`
	ID            string        `json:"id"`
	Key           string        `json:"key"`
	Transition    Transition    `json:"transition"`
	Type          string        `json:"type"`
}

// PrimitiveValues is auto generated by github.com/perrito666/LAC from a json file
type PrimitiveValues struct {
	Limit float64 `json:"limit"`
	Value float64 `json:"value"`
}

// Priority is auto generated by github.com/perrito666/LAC from a json file
type Priority struct {
	Description string `json:"description"`
	IconURL     string `json:"iconUrl"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
	StatusColor string `json:"statusColor"`
}

// Project is auto generated by github.com/perrito666/LAC from a json file
type Project struct {
	AssigneeType    string                  `json:"assigneeType"`
	AvatarUrls      AvatarURLs              `json:"avatarUrls"`
	Components      []Components            `json:"components"`
	Description     string                  `json:"description"`
	Email           string                  `json:"email"`
	ID              string                  `json:"id"`
	Insight         Insight                 `json:"insight"`
	IssueTypes      []ProjectJSONIssueTypes `json:"issueTypes"`
	Key             string                  `json:"key"`
	Lead            Lead                    `json:"lead"`
	Name            string                  `json:"name"`
	ProjectCategory ProjectCategory         `json:"projectCategory"`
	Properties      Properties              `json:"properties"`
	Roles           Roles                   `json:"roles"`
	Self            string                  `json:"self"`
	Simplified      bool                    `json:"simplified"`
	Style           string                  `json:"style"`
	URL             string                  `json:"url"`
	Versions        []interface{}           `json:"versions"`
}

// ProjectAvatars is auto generated by github.com/perrito666/LAC from a json file
type ProjectAvatars struct {
	Custom []Custom `json:"custom"`
	System []System `json:"system"`
}

// ProjectCategory is auto generated by github.com/perrito666/LAC from a json file
type ProjectCategory struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
}

// ProjectEmailAddress is auto generated by github.com/perrito666/LAC from a json file
type ProjectEmailAddress struct {
	EmailAddress string `json:"emailAddress"`
}

// ProjectIDentifiers is auto generated by github.com/perrito666/LAC from a json file
type ProjectIDentifiers struct {
	ID   float64 `json:"id"`
	Key  string  `json:"key"`
	Self string  `json:"self"`
}

// ProjectIssueSecurityLevels is auto generated by github.com/perrito666/LAC from a json file
type ProjectIssueSecurityLevels struct {
	Levels []Levels `json:"levels"`
}

// ProjectIssueTypeHierarchy is auto generated by github.com/perrito666/LAC from a json file
type ProjectIssueTypeHierarchy struct {
	Hierarchy []Hierarchy `json:"hierarchy"`
	ProjectID float64     `json:"projectId"`
}

// ProjectPermissions is auto generated by github.com/perrito666/LAC from a json file
type ProjectPermissions struct {
	Issues     float64 `json:"issues"`
	Permission string  `json:"permission"`
	Projects   float64 `json:"projects"`
}

// ProjectRole is auto generated by github.com/perrito666/LAC from a json file
type ProjectRole struct {
	Actors []Actors `json:"actors"`
}

// ProjectType is auto generated by github.com/perrito666/LAC from a json file
type ProjectType struct {
	Color              string `json:"color"`
	DescriptionI18nKey string `json:"descriptionI18nKey"`
	FormattedKey       string `json:"formattedKey"`
	Icon               string `json:"icon"`
	Key                string `json:"key"`
}

// Projects is auto generated by github.com/perrito666/LAC from a json file
type Projects struct {
	AvatarUrls AvatarURLs   `json:"avatarUrls"`
	ID         string       `json:"id"`
	Issuetypes []Issuetypes `json:"issuetypes"`
	Key        string       `json:"key"`
	Name       string       `json:"name"`
	Self       string       `json:"self"`
}

// Projects2 is auto generated by github.com/perrito666/LAC from a json file
type Projects2 struct {
	Attributes string  `json:"attributes"`
	ID         float64 `json:"id"`
}

// Properties is auto generated by github.com/perrito666/LAC from a json file
type Properties struct {
	Description   string  `json:"description"`
	Founded       string  `json:"founded"`
	IssueEditable bool    `json:"issueEditable"`
	Leader        Leader  `json:"leader"`
	Members       float64 `json:"members"`
	PropertyKey   string  `json:"propertyKey"`
}

// PropertyKeys is auto generated by github.com/perrito666/LAC from a json file
type PropertyKeys struct {
	Keys []Keys `json:"keys"`
}

// Queries is auto generated by github.com/perrito666/LAC from a json file
type Queries struct {
	Query     string    `json:"query"`
	Structure Structure `json:"structure"`
}

// QueriesWithUnknownUsers is auto generated by github.com/perrito666/LAC from a json file
type QueriesWithUnknownUsers struct {
	ConvertedQuery string `json:"convertedQuery"`
	OriginalQuery  string `json:"originalQuery"`
}

// RealAssignee is auto generated by github.com/perrito666/LAC from a json file
type RealAssignee struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	AvatarUrls  AvatarURLs `json:"avatarUrls"`
	DisplayName string     `json:"displayName"`
	Key         string     `json:"key"`
	Name        string     `json:"name"`
	Self        string     `json:"self"`
}

// Records is auto generated by github.com/perrito666/LAC from a json file
type Records struct {
	AssociatedItems []AssociatedItems `json:"associatedItems"`
	AuthorAccountID string            `json:"authorAccountId"`
	AuthorKey       string            `json:"authorKey"`
	Category        string            `json:"category"`
	ChangedValues   []ChangedValues   `json:"changedValues"`
	Created         string            `json:"created"`
	Description     string            `json:"description"`
	EventSource     string            `json:"eventSource"`
	ID              float64           `json:"id"`
	ObjectItem      ObjectItem        `json:"objectItem"`
	RemoteAddress   string            `json:"remoteAddress"`
	Summary         string            `json:"summary"`
}

// RemoteIssueLink is auto generated by github.com/perrito666/LAC from a json file
type RemoteIssueLink struct {
	Application  Application `json:"application"`
	GlobalID     string      `json:"globalId"`
	ID           float64     `json:"id"`
	Object       Object      `json:"object"`
	Relationship string      `json:"relationship"`
	Self         string      `json:"self"`
}

// RemoteIssueLinkIDentifies is auto generated by github.com/perrito666/LAC from a json file
type RemoteIssueLinkIDentifies struct {
	ID   float64 `json:"id"`
	Self string  `json:"self"`
}

// Resolution is auto generated by github.com/perrito666/LAC from a json file
type Resolution struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
}

// Results is auto generated by github.com/perrito666/LAC from a json file
type Results struct {
	DisplayName string   `json:"displayName"`
	Errors      []Errors `json:"errors"`
	Expression  string   `json:"expression"`
	ValID       bool     `json:"valid"`
	Value       string   `json:"value"`
}

// Roles is auto generated by github.com/perrito666/LAC from a json file
type Roles struct {
	Developers string `json:"Developers"`
}

// RuleUpdateErrors is auto generated by github.com/perrito666/LAC from a json file
type RuleUpdateErrors struct {
	ExampleRuleID string `json:"example-rule-id"`
}

// Rules is auto generated by github.com/perrito666/LAC from a json file
type Rules struct {
	Conditions    []Conditions    `json:"conditions"`
	PostFunctions []PostFunctions `json:"postFunctions"`
	Validators    []Validators    `json:"validators"`
}

// Schema is auto generated by github.com/perrito666/LAC from a json file
type Schema struct {
	Custom   string  `json:"custom"`
	CustomID float64 `json:"customId"`
	Items    string  `json:"items"`
	Type     string  `json:"type"`
}

// Scope is auto generated by github.com/perrito666/LAC from a json file
type Scope struct {
	Global    Global        `json:"global"`
	Project   Project       `json:"project"`
	Projects  []interface{} `json:"projects"`
	Projects2 []Projects2   `json:"projects2"`
	Type      string        `json:"type"`
}

// Screen is auto generated by github.com/perrito666/LAC from a json file
type Screen struct {
	Description string  `json:"description"`
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
}

// ScreenSchemeID is auto generated by github.com/perrito666/LAC from a json file
type ScreenSchemeID struct {
	ID float64 `json:"id"`
}

// ScreenableField is auto generated by github.com/perrito666/LAC from a json file
type ScreenableField struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// ScreenableTab is auto generated by github.com/perrito666/LAC from a json file
type ScreenableTab struct {
	ID   float64 `json:"id"`
	Name string  `json:"name"`
}

// Screens is auto generated by github.com/perrito666/LAC from a json file
type Screens struct {
	Create  float64 `json:"create"`
	Default float64 `json:"default"`
	Edit    float64 `json:"edit"`
	View    float64 `json:"view"`
}

// SearchResults is auto generated by github.com/perrito666/LAC from a json file
type SearchResults struct {
	Expand          string   `json:"expand"`
	Issues          []Issues `json:"issues"`
	MaxResults      float64  `json:"maxResults"`
	StartAt         float64  `json:"startAt"`
	Total           float64  `json:"total"`
	WarningMessages string   `json:"warningMessages"`
}

// SecurityLevel is auto generated by github.com/perrito666/LAC from a json file
type SecurityLevel struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
}

// SecurityScheme is auto generated by github.com/perrito666/LAC from a json file
type SecurityScheme struct {
	DefaultSecurityLevelID float64  `json:"defaultSecurityLevelId"`
	Description            string   `json:"description"`
	ID                     float64  `json:"id"`
	Levels                 []Levels `json:"levels"`
	Name                   string   `json:"name"`
	Self                   string   `json:"self"`
}

// SecuritySchemes is auto generated by github.com/perrito666/LAC from a json file
type SecuritySchemes struct {
	IssueSecuritySchemes []IssueSecuritySchemes `json:"issueSecuritySchemes"`
}

// ServerInformation is auto generated by github.com/perrito666/LAC from a json file
type ServerInformation struct {
	BaseURL        string        `json:"baseUrl"`
	BuildDate      string        `json:"buildDate"`
	BuildNumber    float64       `json:"buildNumber"`
	DefaultLocale  DefaultLocale `json:"defaultLocale"`
	ScmInfo        string        `json:"scmInfo"`
	ServerTime     string        `json:"serverTime"`
	ServerTitle    string        `json:"serverTitle"`
	Version        string        `json:"version"`
	VersionNumbers float64       `json:"versionNumbers"`
}

// SharePermission is auto generated by github.com/perrito666/LAC from a json file
type SharePermission struct {
	ID   float64 `json:"id"`
	Type string  `json:"type"`
}

// SharePermissions is auto generated by github.com/perrito666/LAC from a json file
type SharePermissions struct {
	Type string `json:"type"`
}

// Status is auto generated by github.com/perrito666/LAC from a json file
type Status struct {
	Description    string         `json:"description"`
	Icon           Icon           `json:"icon"`
	IconURL        string         `json:"iconUrl"`
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Resolved       bool           `json:"resolved"`
	Self           string         `json:"self"`
	StatusCategory StatusCategory `json:"statusCategory"`
}

// StatusCategory is auto generated by github.com/perrito666/LAC from a json file
type StatusCategory struct {
	ColorName string  `json:"colorName"`
	ID        float64 `json:"id"`
	Key       string  `json:"key"`
	Name      string  `json:"name"`
	Self      string  `json:"self"`
}

// StatusDetails is auto generated by github.com/perrito666/LAC from a json file
type StatusDetails struct {
	Description    string         `json:"description"`
	IconURL        string         `json:"iconUrl"`
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Self           string         `json:"self"`
	StatusCategory StatusCategory `json:"statusCategory"`
}

// Statuses is auto generated by github.com/perrito666/LAC from a json file
type Statuses struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Properties Properties `json:"properties"`
}

// Steps is auto generated by github.com/perrito666/LAC from a json file
type Steps struct {
	Limit float64 `json:"limit"`
	Value float64 `json:"value"`
}

// Structure is auto generated by github.com/perrito666/LAC from a json file
type Structure struct {
	OrderBy OrderBy `json:"orderBy"`
	Where   Where   `json:"where"`
}

// SubTasks is auto generated by github.com/perrito666/LAC from a json file
type SubTasks struct {
	ID           string       `json:"id"`
	OutwardIssue OutwardIssue `json:"outwardIssue"`
	Type         Type         `json:"type"`
}

// Subscriptions is auto generated by github.com/perrito666/LAC from a json file
type Subscriptions struct {
	EndIndex   float64       `json:"end-index"`
	Items      []interface{} `json:"items"`
	MaxResults float64       `json:"max-results"`
	Size       float64       `json:"size"`
	StartIndex float64       `json:"start-index"`
}

// Summary is auto generated by github.com/perrito666/LAC from a json file
type Summary struct {
	AllowedValues   string `json:"allowedValues"`
	DefaultValue    string `json:"defaultValue"`
	HasDefaultValue bool   `json:"hasDefaultValue"`
	Key             string `json:"key"`
	Name            string `json:"name"`
	Operations      string `json:"operations"`
	Required        bool   `json:"required"`
	Schema          Schema `json:"schema"`
}

// System is auto generated by github.com/perrito666/LAC from a json file
type System struct {
	ID             string `json:"id"`
	IsDeletable    bool   `json:"isDeletable"`
	IsSelected     bool   `json:"isSelected"`
	IsSystemAvatar bool   `json:"isSystemAvatar"`
	URLs           URLs   `json:"urls"`
}

// SystemAvatars is auto generated by github.com/perrito666/LAC from a json file
type SystemAvatars struct {
	System []System `json:"system"`
}

// TaskProgressBeanObject is auto generated by github.com/perrito666/LAC from a json file
type TaskProgressBeanObject struct {
	Description    string  `json:"description"`
	ElapsedRuntime float64 `json:"elapsedRuntime"`
	Finished       float64 `json:"finished"`
	ID             string  `json:"id"`
	LastUpdate     float64 `json:"lastUpdate"`
	Progress       float64 `json:"progress"`
	Result         string  `json:"result"`
	Self           string  `json:"self"`
	Started        float64 `json:"started"`
	Status         string  `json:"status"`
	Submitted      float64 `json:"submitted"`
	SubmittedBy    float64 `json:"submittedBy"`
}

// TimeTrackingConfiguration is auto generated by github.com/perrito666/LAC from a json file
type TimeTrackingConfiguration struct {
	DefaultUnit        string  `json:"defaultUnit"`
	TimeFormat         string  `json:"timeFormat"`
	WorkingDaysPerWeek float64 `json:"workingDaysPerWeek"`
	WorkingHoursPerDay float64 `json:"workingHoursPerDay"`
}

// TimeTrackingProvider is auto generated by github.com/perrito666/LAC from a json file
type TimeTrackingProvider struct {
	Key  string `json:"key"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

// Timetracking is auto generated by github.com/perrito666/LAC from a json file
type Timetracking struct {
	OriginalEstimate         string  `json:"originalEstimate"`
	OriginalEstimateSeconds  float64 `json:"originalEstimateSeconds"`
	RemainingEstimate        string  `json:"remainingEstimate"`
	RemainingEstimateSeconds float64 `json:"remainingEstimateSeconds"`
	TimeSpent                string  `json:"timeSpent"`
	TimeSpentSeconds         float64 `json:"timeSpentSeconds"`
}

// To is auto generated by github.com/perrito666/LAC from a json file
type To struct {
	Description    string         `json:"description"`
	IconURL        string         `json:"iconUrl"`
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Self           string         `json:"self"`
	StatusCategory StatusCategory `json:"statusCategory"`
}

// Transition is auto generated by github.com/perrito666/LAC from a json file
type Transition struct {
	ErrorCollection ErrorCollection `json:"errorCollection"`
	ID              float64         `json:"id"`
	Name            string          `json:"name"`
	Status          float64         `json:"status"`
}

// Transitions is auto generated by github.com/perrito666/LAC from a json file
type Transitions struct {
	Fields        Fields        `json:"fields"`
	HasScreen     bool          `json:"hasScreen"`
	ID            string        `json:"id"`
	IsAvailable   bool          `json:"isAvailable"`
	IsConditional bool          `json:"isConditional"`
	IsGlobal      bool          `json:"isGlobal"`
	IsInitial     bool          `json:"isInitial"`
	Name          string        `json:"name"`
	To            To            `json:"to"`
	Transitions   []Transitions `json:"transitions"`
}

// TransitionsScreen is auto generated by github.com/perrito666/LAC from a json file
type TransitionsScreen struct {
	ID string `json:"id"`
}

// Type is auto generated by github.com/perrito666/LAC from a json file
type Type struct {
	ID      string `json:"id"`
	Inward  string `json:"inward"`
	Name    string `json:"name"`
	Outward string `json:"outward"`
	Self    string `json:"self"`
}

// UpdateAuthor is auto generated by github.com/perrito666/LAC from a json file
type UpdateAuthor struct {
	AccountID   string `json:"accountId"`
	Active      bool   `json:"active"`
	DisplayName string `json:"displayName"`
	Self        string `json:"self"`
}

// UpdateResults is auto generated by github.com/perrito666/LAC from a json file
type UpdateResults struct {
	RuleUpdateErrors RuleUpdateErrors `json:"ruleUpdateErrors"`
	UpdateErrors     []interface{}    `json:"updateErrors"`
	WorkflowID       WorkflowID       `json:"workflowId"`
}

// UpdatedProjectCategory is auto generated by github.com/perrito666/LAC from a json file
type UpdatedProjectCategory struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Self        string `json:"self"`
}

// URLs is auto generated by github.com/perrito666/LAC from a json file
type URLs struct {
	N16x16 string `json:"16x16"`
	N24x24 string `json:"24x24"`
	N32x32 string `json:"32x32"`
	N48x48 string `json:"48x48"`
}

// User is auto generated by github.com/perrito666/LAC from a json file
type User struct {
	AccountID        string           `json:"accountId"`
	Active           bool             `json:"active"`
	ApplicationRoles ApplicationRoles `json:"applicationRoles"`
	AvatarUrls       AvatarURLs       `json:"avatarUrls"`
	DisplayName      string           `json:"displayName"`
	EmailAddress     string           `json:"emailAddress"`
	Groups           Groups           `json:"groups"`
	Key              string           `json:"key"`
	Name             string           `json:"name"`
	Self             string           `json:"self"`
	TimeZone         string           `json:"timeZone"`
}

// Users is auto generated by github.com/perrito666/LAC from a json file
type Users struct {
	AccountID   string  `json:"accountId"`
	AccountType string  `json:"accountType"`
	AvatarURL   string  `json:"avatarUrl"`
	DisplayName string  `json:"displayName"`
	EndIndex    float64 `json:"end-index"`
	Header      string  `json:"header"`
	HTML        string  `json:"html"`
	Items       []Items `json:"items"`
	Key         string  `json:"key"`
	MaxResults  float64 `json:"max-results"`
	Name        string  `json:"name"`
	Size        float64 `json:"size"`
	StartIndex  float64 `json:"start-index"`
	Total       float64 `json:"total"`
	Users       []Users `json:"users"`
}

// Validators is auto generated by github.com/perrito666/LAC from a json file
type Validators struct {
	Configuration Configuration `json:"configuration"`
	ID            string        `json:"id"`
	Key           string        `json:"key"`
	Transition    Transition    `json:"transition"`
	Type          string        `json:"type"`
}

// Values is auto generated by github.com/perrito666/LAC from a json file
type Values struct {
	AccountID                  string                `json:"accountId"`
	AccountType                string                `json:"accountType"`
	Active                     bool                  `json:"active"`
	ApplicationRoles           ApplicationRoles      `json:"applicationRoles"`
	Archived                   bool                  `json:"archived"`
	Assignee                   Assignee              `json:"assignee"`
	AssigneeType               string                `json:"assigneeType"`
	Author                     Author                `json:"author"`
	AvatarUrls                 AvatarURLs            `json:"avatarUrls"`
	Body                       Body                  `json:"body"`
	ComponentBean              ComponentBean         `json:"componentBean"`
	Conditions                 []Conditions          `json:"conditions"`
	ContextsCount              float64               `json:"contextsCount"`
	Created                    string                `json:"created"`
	DefaultIssueTypeID         string                `json:"defaultIssueTypeId"`
	Description                string                `json:"description"`
	DisplayName                string                `json:"displayName"`
	EmailAddress               string                `json:"emailAddress"`
	Favourite                  bool                  `json:"favourite"`
	FavouritedCount            float64               `json:"favouritedCount"`
	FieldConfigurationID       string                `json:"fieldConfigurationId"`
	FieldConfigurationSchemeID string                `json:"fieldConfigurationSchemeId"`
	GroupID                    string                `json:"groupId"`
	Groups                     Groups                `json:"groups"`
	ID                         string                `json:"id"`
	Insight                    Insight               `json:"insight"`
	IsAssigneeTypeValID        bool                  `json:"isAssigneeTypeValid"`
	IsDefault                  bool                  `json:"isDefault"`
	IsHidden                   bool                  `json:"isHidden"`
	IsLocked                   bool                  `json:"isLocked"`
	IsRequired                 bool                  `json:"isRequired"`
	IssueCount                 float64               `json:"issueCount"`
	IssueTypeID                string                `json:"issueTypeId"`
	IssueTypeScheme            IssueTypeScheme       `json:"issueTypeScheme"`
	IssueTypeSchemeID          string                `json:"issueTypeSchemeId"`
	IssueTypeScreenScheme      IssueTypeScreenScheme `json:"issueTypeScreenScheme"`
	IssueTypeScreenSchemeID    string                `json:"issueTypeScreenSchemeId"`
	Items                      []Items               `json:"items"`
	Jql                        string                `json:"jql"`
	Key                        string                `json:"key"`
	LastUsed                   LastUsed              `json:"lastUsed"`
	Lead                       Lead                  `json:"lead"`
	Name                       string                `json:"name"`
	Overdue                    bool                  `json:"overdue"`
	Owner                      Owner                 `json:"owner"`
	PostFunctions              []PostFunctions       `json:"postFunctions"`
	Project                    string                `json:"project"`
	ProjectCategory            ProjectCategory       `json:"projectCategory"`
	ProjectID                  float64               `json:"projectId"`
	ProjectIds                 string                `json:"projectIds"`
	Properties                 []interface{}         `json:"properties"`
	RealAssignee               RealAssignee          `json:"realAssignee"`
	RealAssigneeType           string                `json:"realAssigneeType"`
	ReleaseDate                string                `json:"releaseDate"`
	Released                   bool                  `json:"released"`
	ScreenSchemeID             string                `json:"screenSchemeId"`
	ScreensCount               float64               `json:"screensCount"`
	SearchURL                  string                `json:"searchUrl"`
	Self                       string                `json:"self"`
	SharePermissions           []interface{}         `json:"sharePermissions"`
	Simplified                 bool                  `json:"simplified"`
	Style                      string                `json:"style"`
	Subscriptions              []interface{}         `json:"subscriptions"`
	TimeZone                   string                `json:"timeZone"`
	UpdateAuthor               UpdateAuthor          `json:"updateAuthor"`
	Updated                    string                `json:"updated"`
	UpdatedTime                float64               `json:"updatedTime"`
	UserReleaseDate            string                `json:"userReleaseDate"`
	Validators                 []Validators          `json:"validators"`
	Value                      string                `json:"value"`
	ViewURL                    string                `json:"viewUrl"`
	Visibility                 Visibility            `json:"visibility"`
	WorkflowID                 WorkflowID            `json:"workflowId"`
	WorkflowScheme             WorkflowScheme        `json:"workflowScheme"`
	WorklogID                  float64               `json:"worklogId"`
}

// ValuesTransitions is auto generated by github.com/perrito666/LAC from a json file
type ValuesTransitions struct {
	Description string            `json:"description"`
	From        string            `json:"from"`
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Rules       Rules             `json:"rules"`
	Screen      TransitionsScreen `json:"screen"`
	To          string            `json:"to"`
	Type        string            `json:"type"`
}

// Version is auto generated by github.com/perrito666/LAC from a json file
type Version struct {
	Archived        bool    `json:"archived"`
	Description     string  `json:"description"`
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Overdue         bool    `json:"overdue"`
	ProjectID       float64 `json:"projectId"`
	ReleaseDate     string  `json:"releaseDate"`
	Released        bool    `json:"released"`
	Self            string  `json:"self"`
	UserReleaseDate string  `json:"userReleaseDate"`
}

// VersionIssueCounts is auto generated by github.com/perrito666/LAC from a json file
type VersionIssueCounts struct {
	CustomFieldUsage                         []CustomFieldUsage `json:"customFieldUsage"`
	IssueCountWithCustomFieldsShowingVersion float64            `json:"issueCountWithCustomFieldsShowingVersion"`
	IssuesAffectedCount                      float64            `json:"issuesAffectedCount"`
	IssuesFixedCount                         float64            `json:"issuesFixedCount"`
	Self                                     string             `json:"self"`
}

// VersionUnresolvedIssuesCount is auto generated by github.com/perrito666/LAC from a json file
type VersionUnresolvedIssuesCount struct {
	IssuesCount           float64 `json:"issuesCount"`
	IssuesUnresolvedCount float64 `json:"issuesUnresolvedCount"`
	Self                  string  `json:"self"`
}

// Visibility is auto generated by github.com/perrito666/LAC from a json file
type Visibility struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

// VisibleFieldNames is auto generated by github.com/perrito666/LAC from a json file
type VisibleFieldNames struct {
	DisplayName string `json:"displayName"`
	Operators   string `json:"operators"`
	Orderable   string `json:"orderable"`
	Searchable  string `json:"searchable"`
	Types       string `json:"types"`
	Value       string `json:"value"`
}

// VisibleFunctionNames is auto generated by github.com/perrito666/LAC from a json file
type VisibleFunctionNames struct {
	DisplayName string `json:"displayName"`
	IsList      string `json:"isList"`
	Types       string `json:"types"`
	Value       string `json:"value"`
}

// Voters is auto generated by github.com/perrito666/LAC from a json file
type Voters struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	AvatarUrls  AvatarURLs `json:"avatarUrls"`
	DisplayName string     `json:"displayName"`
	Key         string     `json:"key"`
	Name        string     `json:"name"`
	Self        string     `json:"self"`
}

// Votes is auto generated by github.com/perrito666/LAC from a json file
type Votes struct {
	HasVoted bool     `json:"hasVoted"`
	Self     string   `json:"self"`
	Voters   []Voters `json:"voters"`
	Votes    float64  `json:"votes"`
}

// Watcher is auto generated by github.com/perrito666/LAC from a json file
type Watcher struct {
	IsWatching bool       `json:"isWatching"`
	Self       string     `json:"self"`
	WatchCount float64    `json:"watchCount"`
	Watchers   []Watchers `json:"watchers"`
}

// Watchers is auto generated by github.com/perrito666/LAC from a json file
type Watchers struct {
	AccountID   string     `json:"accountId"`
	Active      bool       `json:"active"`
	DisplayName string     `json:"displayName"`
	IsWatching  bool       `json:"isWatching"`
	Self        string     `json:"self"`
	WatchCount  float64    `json:"watchCount"`
	Watchers    []Watchers `json:"watchers"`
}

// WebhookRegistrationResult is auto generated by github.com/perrito666/LAC from a json file
type WebhookRegistrationResult struct {
	CreatedWebhookID float64 `json:"createdWebhookId"`
}

// WebhooksExpirationDate is auto generated by github.com/perrito666/LAC from a json file
type WebhooksExpirationDate struct {
	ExpirationDate string `json:"expirationDate"`
}

// Where is auto generated by github.com/perrito666/LAC from a json file
type Where struct {
	Clauses  []Clauses `json:"clauses"`
	Operator string    `json:"operator"`
}

// WorkflowID is auto generated by github.com/perrito666/LAC from a json file
type WorkflowID struct {
	Draft bool   `json:"draft"`
	Name  string `json:"name"`
}

// WorkflowScheme is auto generated by github.com/perrito666/LAC from a json file
type WorkflowScheme struct {
	DefaultWorkflow   string            `json:"defaultWorkflow"`
	Description       string            `json:"description"`
	Draft             bool              `json:"draft"`
	ID                float64           `json:"id"`
	IssueTypeMappings IssueTypeMappings `json:"issueTypeMappings"`
	Name              string            `json:"name"`
	Self              string            `json:"self"`
}

// WorkflowTransitionProperty is auto generated by github.com/perrito666/LAC from a json file
type WorkflowTransitionProperty struct {
	ID    string `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

// WorkflowTransitionRulesUpdateErrors is auto generated by github.com/perrito666/LAC from a json file
type WorkflowTransitionRulesUpdateErrors struct {
	UpdateResults []UpdateResults `json:"updateResults"`
}

// Worklog is auto generated by github.com/perrito666/LAC from a json file
type Worklog struct {
	Author           Author       `json:"author"`
	Comment          Comment      `json:"comment"`
	ID               string       `json:"id"`
	IssueID          string       `json:"issueId"`
	Self             string       `json:"self"`
	Started          string       `json:"started"`
	TimeSpent        string       `json:"timeSpent"`
	TimeSpentSeconds float64      `json:"timeSpentSeconds"`
	UpdateAuthor     UpdateAuthor `json:"updateAuthor"`
	Updated          string       `json:"updated"`
	Visibility       Visibility   `json:"visibility"`
}

// Worklogs is auto generated by github.com/perrito666/LAC from a json file
type Worklogs struct {
	Author           Author       `json:"author"`
	Comment          Comment      `json:"comment"`
	ID               string       `json:"id"`
	IssueID          string       `json:"issueId"`
	Self             string       `json:"self"`
	Started          string       `json:"started"`
	TimeSpent        string       `json:"timeSpent"`
	TimeSpentSeconds float64      `json:"timeSpentSeconds"`
	UpdateAuthor     UpdateAuthor `json:"updateAuthor"`
	Updated          string       `json:"updated"`
	Visibility       Visibility   `json:"visibility"`
}
